[ROB-2094] better supabase error on dns error (#1091)
on failure to connect to supabase it now prints error like
```
holmes.core.supabase_dal.SupabaseDnsException:
AuthRetryableError: [Errno -2] Name or service not known
Cannot connect to Robusta SaaS <https://hfzzthymmksjyasfrdefd.supabase.co>.
This is often due to DNS issues or Firewall policies.
Please run the following command in your cluster and verify it does not print 'Could not resolve host':
curl -I https://hfzzthymmksjyasfrdefd.supabase.co
```