Add support for AWS_PROFILE in Bedrock model requirements (#400)
Update code to support AWS Bedrock, so we could just pass profile name
instead of hardcoding AWS credentials each time. Currently it returns
error:
```
│ /holmesgpt/holmes/core/llm.py:73 in │
│ __init__                                                                     │
│                                                                              │
│    70 │   │   self.args = args                                               │
│    71 │   │                                                                  │
│    72 │   │   if not args:                                                   │
│ ❱  73 │   │   │   self.check_llm(self.model, self.api_key)                   │
│    74 │                                                                      │
│    75 │   def check_llm(self, model: str, api_key: Optional[str]):           │
│    76 │   │   logging.debug(f"Checking LiteLLM model {model}")               │
│                                                                              │
│ /holmesgpt/holmes/core/llm.py:125   │
│ in check_llm                                                                 │
│                                                                              │
│   122 │   │   │   model_requirements = litellm.validate_environment(model=mo │
│   123 │   │                                                                  │
│   124 │   │   if not model_requirements["keys_in_environment"]:              │
│ ❱ 125 │   │   │   raise Exception(                                           │
│   126 │   │   │   │   f"model {model} requires the following environment var │
│   127 │   │   │   )                                                          │
│   128                                                                        │
╰──────────────────────────────────────────────────────────────────────────────╯
Exception: model bedrock/us.anthropic.claude-3-7-sonnet-20250219-v1:0 requires 
the following environment variables: ['AWS_ACCESS_KEY_ID', 
'AWS_SECRET_ACCESS_KEY']


```

Co-authored-by: arik <alon.arik@gmail.com>