Update build-and-deploy-docs.yaml (#686)
Docs are failing because GitHub actions used Python version 3.13.5. But
module was removed in version Python 3.12
([details](https://docs.python.org/3/library/distutils.html)).
```
Error output:
Traceback (most recent call last):
  File "<stdin>", line 9, in <module>
ModuleNotFoundError: No module named 'distutils'
```

Tested this fix on my account here
https://github.com/pavangudiwada/holmesgpt/actions/runs/16450522228/job/46494249324
Here's the change
https://github.com/pavangudiwada/holmesgpt/blob/7e20ddf4f188ec2204265de5406463b8434864f4/.github/workflows/build-and-deploy-docs.yaml#L19